# Generated by Django 5.2.5 on 2026-06-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySalaryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_entries', models.PositiveIntegerField()),
                ('data_quality_score', models.FloatField(default=0.0, help_text='0-1 score indicating data reliability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['industry', 'year'], name='analytics_a_industr_6264cc_idx'), models.Index(fields=['job_title'], name='analytics_a_job_tit_08750c_idx')],
                'unique_together': {('industry', 'year', 'month', 'job_title')},
            },
        ),
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('highest_paying_industry', 'Highest Paying Industry'), ('fastest_growing_role', 'Fastest Growing Role'), ('market_trend', 'Market Trend'), ('skill_demand', 'Skill Demand'), ('compensation_insight', 'Compensation Insight')], max_length=100)),
                ('data', models.JSONField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='0-1 confidence in this insight')),
                ('source_data_count', models.PositiveIntegerField(help_text='Number of data points used')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence_score'],
                'indexes': [models.Index(fields=['category'], name='analytics_a_categor_0e31be_idx'), models.Index(fields=['valid_until'], name='analytics_a_valid_u_19083d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyRankingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rank', models.PositiveIntegerField()),
                ('reputation_score', models.FloatField()),
                ('review_count', models.PositiveIntegerField()),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recommendation_percentage', models.FloatField()),
                ('industry_rank', models.PositiveIntegerField()),
                ('growth_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_cache', to='companies.company')),
            ],
            options={
                'ordering': ['overall_rank'],
                'indexes': [models.Index(fields=['overall_rank'], name='analytics_a_overall_89d032_idx'), models.Index(fields=['industry_rank'], name='analytics_a_industr_aabab8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('p25', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('p50', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('p75', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('median_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_points_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_benchmarks', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['job_title'], name='analytics_a_job_tit_a17d35_idx'), models.Index(fields=['experience_level'], name='analytics_a_experie_a215c2_idx'), models.Index(fields=['location'], name='analytics_a_locatio_809451_idx'), models.Index(fields=['last_updated'], name='analytics_a_last_up_9e949d_idx')],
                'unique_together': {('company', 'job_title', 'experience_level', 'location')},
            },
        ),
    ]
