# Generated by Django 6.0.5 on 2026-05-24 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('normalized_job_title', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Internship')], max_length=50)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_benefits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_fairness_rating', models.PositiveSmallIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_note', models.TextField(blank=True, null=True)),
                ('total_compensation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='compensatio_company_4251df_idx'), models.Index(fields=['normalized_job_title'], name='compensatio_normali_e2d775_idx'), models.Index(fields=['experience_level'], name='compensatio_experie_83d270_idx'), models.Index(fields=['location'], name='compensatio_locatio_cebfa1_idx')],
            },
        ),
    ]
