# Generated by Django 5.2.5 on 2026-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='anonymous_reference',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
