# Generated by Django 5.2.5 on 2026-06-01 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('review_submission', 'Review Submission'), ('compensation_submission', 'Compensation Submission'), ('benchmark_access', 'Benchmark Access'), ('admin_adjustment', 'Admin Adjustment'), ('referral_bonus', 'Referral Bonus')], max_length=50)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='Reference to related review/compensation ID', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_cr_user_id_764de8_idx'), models.Index(fields=['transaction_type'], name='accounts_cr_transac_7e43ca_idx'), models.Index(fields=['status'], name='accounts_cr_status_2c66d4_idx')],
            },
        ),
    ]
