# Generated by Django 6.0.5 on 2026-05-24 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_brand_value', models.PositiveSmallIntegerField()),
                ('work_environment', models.PositiveSmallIntegerField()),
                ('career_growth', models.PositiveSmallIntegerField()),
                ('salary_satisfaction', models.PositiveSmallIntegerField()),
                ('fringe_benefits', models.PositiveSmallIntegerField()),
                ('job_security', models.PositiveSmallIntegerField()),
                ('employee_respect', models.PositiveSmallIntegerField()),
                ('management_quality', models.PositiveSmallIntegerField()),
                ('work_life_balance', models.PositiveSmallIntegerField()),
                ('learning_opportunity', models.PositiveSmallIntegerField()),
                ('overall_recommendation', models.CharField(choices=[('yes', 'Yes'), ('neutral', 'Neutral'), ('no', 'No')], max_length=20)),
                ('anonymous', models.BooleanField(default=True)),
                ('anonymous_reference', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_note', models.TextField(blank=True, null=True)),
                ('weighted_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='reviews_com_company_9fbb98_idx'), models.Index(fields=['is_verified'], name='reviews_com_is_veri_3bfa40_idx'), models.Index(fields=['is_flagged'], name='reviews_com_is_flag_8da13a_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
