# Generated by Django 6.0.5 on 2026-05-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
