# Generated by Django 6.0.5 on 2026-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('company_type', models.CharField(choices=[('local', 'Local'), ('mnc', 'Multinational'), ('startup', 'Startup')], max_length=20)),
                ('industry', models.CharField(choices=[('software', 'Software'), ('banking', 'Banking'), ('telecom', 'Telecom'), ('healthcare', 'Healthcare'), ('ecommerce', 'E-Commerce')], max_length=100)),
                ('manpower_size', models.CharField(choices=[('1-50', '1-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=20)),
                ('headquarters', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('compensation_count', models.PositiveIntegerField(default=0)),
                ('reputation_index', models.FloatField(default=0)),
                ('average_salary_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='companies_c_name_2d8260_idx'), models.Index(fields=['industry'], name='companies_c_industr_6efa2c_idx'), models.Index(fields=['verified'], name='companies_c_verifie_10d24c_idx')],
            },
        ),
    ]
